"""Clean schema baseline (schema version 1).

Single reset baseline: the server database starts empty, so no historical
upgrade path is carried. This revision materializes the full current model
metadata as the version 1 schema, so ``alembic upgrade head`` reproducibly
builds a working database instead of relying on application-startup
``create_all``. Future schema changes should be added as new autogenerated
revisions stacked on top of this baseline.

Revision ID: 20260624_1000
Revises:
Create Date: 2026-06-24 18:10:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
from app.models import Base

# revision identifiers, used by Alembic.
revision: str = "20260624_1000"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
